services:
  - type: web
    name: focusvault-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: MONGO_URI
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_USERNAME
        sync: false
      - key: PORT
        value: 5000
